name = "HOTDOCS"
license = "BSD-2"
licenselink = "https://github.com/hotosm/hotdocs/blob/master/LICENSE"
description = "theme for Humanitarian OpenStreetMap Team documentation sites"
homepage = "https://github.com/hotosm/hotdocs"
tags = []
features = []
min_version = "0.41"

[author]
  name = "HOTOSM"
  homepage = "https://hotosm.org"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
